**Задание на повторение материала
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
import numpy as np
a=np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
a1=a.reshape(12, 1)
a2=a.reshape(6, 2)
a3=a.reshape(4, 3)
a4=a.reshape(3, 4)
a5=a.reshape(2, 6)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [4]:
a1=a.reshape(2, -1)
a2=a.reshape(3, -1)
a3=a.reshape(2, -1)
a4=a.reshape(4, -1)
a5=a.reshape(12, -1)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [12]:
a=np.arange(1, 13)
b=a.reshape(12,-1)
print(a)
print(b)
print(b[2])
print(b[2,0])

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
[3]
3


Массив из 12 строк считается двухмерным, таким образом назвать его одномерным нельзя

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [22]:
b=np.random.randn(3,4)
print(b)
print(b.size)
c=b.flatten()
print(c)
print(c.size)

[[-0.96899575 -0.46922096  1.07300795  0.24407671]
 [-1.42939429 -0.02257777 -0.13250873  0.09926041]
 [ 1.34214618  0.25460859 -1.74923237  1.23919208]]
12
[-0.96899575 -0.46922096  1.07300795  0.24407671 -1.42939429 -0.02257777
 -0.13250873  0.09926041  1.34214618  0.25460859 -1.74923237  1.23919208]
12


Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [23]:
a=np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [24]:
b=np.arange(20, 1, -2).reshape(1,10)
print(b)

[[20 18 16 14 12 10  8  6  4  2]]


Массив b двумерный a-одномерный

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [32]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
print(a)
print(b)
res = np.vstack((a, b))
print(res.size)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
10


Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B?

In [43]:
a=np.arange(0, 12)
print(a)
A=a.reshape(4,3)
print(A)
At=A.transpose()
print(At)
B = np.dot(A,At)
print(B)
print(B.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
(4, 4)


 Получится ли вычислить обратную матрицу для матрицы B и почему?

In [42]:
B_inv=np.linalg.inv(B)
#Вычисление не работает, матрица сингулярная (вырожденная), её определитель равен нулю

LinAlgError: ignored

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [44]:
np.random.seed(42)

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [47]:
c=np.random.randint(0, 16,16)

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.

In [48]:
C=c.reshape(4,4)
D=B+C*10

Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [56]:
d=np.linalg.det(D)
print(d)
r=np.linalg.matrix_rank(D)
print(r)
D_inv=np.linalg.inv(D)
print(D_inv)


-28511999.999999944
4
[[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. 

In [57]:
D_inv=np.where(D_inv<0, 0,1)
print(D_inv)

[[1 1 1 0]
 [0 0 0 1]
 [0 0 0 1]
 [1 0 1 0]]


С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [60]:
print(B)
print(C)
E=np.where(D_inv==1, B, C)
print(E)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]
[[  5  14  23  14]
 [ 10   7  12 122]
 [  6   9   2 212]
 [ 32  10 212   4]]
